apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-system
  name: flask-webapp
  labels:
    app: flask-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-webapp
  template:
    metadata:
      labels:
        app: flask-webapp
    spec:
      containers:
        - name: flask-webapp
          image: zeepeebee30/hw-flask:latest
          ports:
            - containerPort: 5000
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: flask-webapp-service
  annotations:
    # Note that the backend talks over HTTP.
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    # TODO: Fill in with the ARN of your certificate.
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-southeast-1:042468190057:certificate/12fd956d-c471-4a64-9241-5aa90b1074b4
    # Only run SSL on the port named "https" below.
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: 'https'
spec:
  ports:
    - name: http
      port: 80
      targetPort: 5000
    - name: https
      port: 443
      targetPort: 5000
  type: LoadBalancer
  selector:
    app: flask-webapp

---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   namespace: kube-system
#   name: ingress
#   annotations:
#     alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-1:042468190057:certificate/12fd956d-c471-4a64-9241-5aa90b1074b4
#     alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
#     alb.ingress.kubernetes.io/ssl-redirect: '443'
# spec:
#   ingressClassName: alb
#   rules:
#     - http:
#         paths:
#           - path: /*
#             pathType: ImplementationSpecific
#             backend:
#               service:
#                 name: flask-webapp-service
#                 port:
#                   number: 5000

