apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-webapp
  labels:
    app: flask-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-webapp
  template:
    metadata:
      labels:
        app: flask-webapp
    spec:
      containers:
        - name: flask-webapp
          image: zeepeebee30/hw-flask:latest
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: flask-webapp-service
spec:
  ports:
    - port: 5000
      targetPort: 5000
      name: http
  selector:
    app: flask-webapp
